image: node:10

variables:
  APP: "angular-shell-schematic"

cache:
  paths:
    - node_modules

before_script:
  - node -v
  - npm -v
  - yarn -v
  - which node
  - which npm
  - which yarn
  - yarn --non-interactive

stages:
  - build
  - test
  - deploy

# Build

.build:
  stage: build
  script:
    - yarn build

build-node-10:
  image: node:10
  extends: .build

build-node-11:
  image: node:11
  extends: .build

# Test

.test:
  stage: test
  script:
    - yarn test

test-node-10:
  image: node:10
  extends: .test

test-node-11:
  image: node:11
  extends: .test

# Deploy

publish:
  stage: deploy
  only:
    variables:
      - $NEW_VERSION
  environment:
    name: production
    url: https://www.npmjs.com/package/angular-shell-schematic
  before_script:
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - git remote set-url origin https://jdat:${PERSONAL_ACCESS_TOKEN}@gitlab.com/jeandat/tools/angular-shell-schematic.git
  script:
    - "yarn version --new-version=$NEW_VERSION
    - git push origin HEAD:master
    - git push origin --tags
    - yarn build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - yarn publish
